# PROJECT SETTINGS and OPTIMIZATION CONSTRAINTS
#-----------------------------------------------------------

project_settings:
  # Project lifetime [years]
  project_lifetime: 20
  # Discount rate
  discount_rate: 0.1
  # Currency
  currency: NOK

optimization_settings:
  # Maximum annual Lost load as share of total demand to avoid overloading the system
  max_lost_load_share: 0.05
  # Maximum CAPEX
  max_capex : 1000000
  # Minimum Renewable Peneration (annual share of total demand) to regulate generator usage (only if generator is enabled)
  min_res_share: 0.0
  # Allow for unit committment for each of the sizing variables (unit of nominal capacity as integer solution). NOTE: This may increase the computation time. 
  solar_integer_solution: false
  battery_integer_solution: false
  generator_integer_solution: false


# TECHNO-ECONOMIC PARAMETERS
#--------------------------------------------------------------

# Solar PV Parameters
solar:
  nominal_capacity: 1         # Nominal capacity of solar PV system in kW
  capex: 7100                 # Specific investment cost per kW
  opex: 0.01                  # Fixed O&M cost as annual share of investment cost
  subsidy: 0.3                # Subsidy as a share of investment cost
  lifetime: 20                # Lifetime of solar PV system in years

# Battery Parameters
battery:
  nominal_capacity: 1     # [kWh] Nominal capacity of battery system
  capex: 3000             # Specific investment cost per nominal capacity
  opex: 0.05              # Fixed O&M cost as annual share of investment cost
  expected_lifetime: 8    # Expected lifetime of battery system in years
  operation:
    charge_time: 5            # [hours] Charging time
    discharge_time: 5         # [hours] Discharging time
  efficiency:
    charge: 0.95              # Charging efficiency
    discharge: 0.95           # Discharging efficiency
  SOC:
    min: 0.2                  # Minimum state of charge 
    max: 0.9                  # Maximum state of charge 
    initial: 0.5              # Initial state of charge

# Backup Generator Parameters
generator:
  enabled: true              # Enable backup generator (true/false)
  nominal_capacity: 1         # Nominal capacity of backup generator in kW
  capex: 1000                 # Specific investment cost per kW
  opex: 0.02                  # Fixed O&M cost as annual share of investment cost
  fuel_lhv: 9.5               # Fuel lower heating value in kWh/liter
  fuel_cost: 5               # Fuel cost per liter
  lifetime: 20                # Lifetime of backup generator in years
  nominal_efficiency: 0.35    # Generator nominal efficiency (used if partial_load is false)
  partial_load: true         # Enable partial load effect (piecewise linear approximation)
  sampling_points: 10          # Number of sampling points for partial load efficiency curve (if enabled)

# SOLVER SETTINGS
#--------------------------------------------------------------

solver_settings:
  # GLPK solver settings
  glpk_options:
    presolve: true      # Use presolve to simplify the problem (true/false)
    msg_lev: 3          # Message level (0-4)
    tm_lim: 10000000    # Time limit in milliseconds for solving the problem
  # Gurobi solver settings
  gurobi_options:
    Method: 2            # Optimization method: 0=primal simplex, 1=dual simplex, 2=barrier
    OutputFlag: 1        # Display solver output (0 = off, 1 = on)
    TimeLimit: 3600      # Time limit in seconds
    MIPGap: 0.001        # Relative MIP optimality gap (e.g., 0.1% gap)